export default {
    "defaults": {
        "sides": "100",
        "chaos": "5",
        "odds": "50/50"
    },
    "actions": [
        "Attainment",
        "Starting",
        "Neglect",
        "Fight",
        "Recruit",
        "Triumph",
        "Violate",
        "Oppose",
        "Malice",
        "Communicate",
        "Persecute",
        "Increase",
        "Decrease",
        "Abandon",
        "Gratify",
        "Inquire",
        "Antagonise",
        "Move",
        "Waste",
        "Truce",
        "Release",
        "Befriend",
        "Judge",
        "Desert",
        "Dominate",
        "Procrastinate",
        "Praise",
        "Separate",
        "Take",
        "Break",
        "Heal",
        "Delay",
        "Stop",
        "Lie",
        "Return",
        "Immitate",
        "Struggle",
        "Inform",
        "Bestow",
        "Postpone",
        "Expose",
        "Haggle",
        "Imprison",
        "Release",
        "Celebrate",
        "Develop",
        "Travel",
        "Block",
        "Harm",
        "Debase",
        "Overindulge",
        "Adjourn",
        "Adversity",
        "Kill",
        "Disrupt",
        "Usurp",
        "Create",
        "Betray",
        "Agree",
        "Abuse",
        "Oppress",
        "Inspect",
        "Ambush",
        "Spy",
        "Attach",
        "Carry",
        "Open",
        "Carelessness",
        "Ruin",
        "Extravagance",
        "Trick",
        "Arrive",
        "Propose",
        "Divide",
        "Refuse",
        "Mistrust",
        "Deceive",
        "Cruelty",
        "Intolerance",
        "Trust",
        "Excitement",
        "Activity",
        "Assist",
        "Care",
        "Negligence",
        "Passion",
        "Work hard",
        "Control",
        "Attract",
        "Failure",
        "Pursue",
        "Vengeance",
        "Proceedings",
        "Dispute",
        "Punish",
        "Guide",
        "Transform",
        "Overthrow",
        "Oppress",
        "Change"
    ],
    "chart": {
        "impossible": {
            9: 50,
            8: 25,
            7: 15,
            6: 10,
            5: 5,
            4: 5,
            3: 0,
            2: 0,
            1: -20
        },
        "no way": {
            9: 75,
            8: 50,
            7: 35,
            6: 25,
            5: 15,
            4: 10,
            3: 5,
            2: 5,
            1: 0
        },
        "very unlikely": {
            9: 85,
            8: 65,
            7: 50,
            6: 45,
            5: 25,
            4: 15,
            3: 10,
            2: 5,
            1: 5
        },
        "unlikely": {
            9: 90,
            8: 75,
            7: 55,
            6: 50,
            5: 35,
            4: 20,
            3: 15,
            2: 10,
            1: 5
        },
        "50/50": {
            9: 95,
            8: 85,
            7: 75,
            6: 65,
            5: 50,
            4: 35,
            3: 25,
            2: 15,
            1: 10
        },
        "somewhat likely": {
            9: 95,
            8: 90,
            7: 85,
            6: 80,
            5: 65,
            4: 50,
            3: 45,
            2: 25,
            1: 20
        },
        "likely": {
            9: 100,
            8: 95,
            7: 90,
            6: 85,
            5: 75,
            4: 55,
            3: 50,
            2: 35,
            1: 25
        },
        "very likely": {
            9: 105,
            8: 95,
            7: 95,
            6: 90,
            5: 85,
            4: 75,
            3: 65,
            2: 50,
            1: 45
        },
        "near sure thing": {
            9: 115,
            8: 100,
            7: 95,
            6: 95,
            5: 90,
            4: 80,
            3: 75,
            2: 55,
            1: 50
        },
        "a sure thing": {
            9: 125,
            8: 110,
            7: 95,
            6: 95,
            5: 90,
            4: 85,
            3: 80,
            2: 65,
            1: 55
        },
        "has to be": {
            9: 145,
            8: 130,
            7: 100,
            6: 100,
            5: 95,
            4: 95,
            3: 90,
            2: 85,
            1: 80
        }
    },
    "focuses": {
        // upper limit : focus
        7: "Remote event",
        28: "NPC action",
        35: "Introduce a new NPC",
        45: "Move toward a thread",
        52: "Move away from a thread",
        55: "Close a thread",
        67: "PC negative",
        75: "PC positive",
        83: "Ambiguous event",
        92: "NPC negative",
        100: "NPC positive"
    },
    "subjects": [
        "Goals",
        "Dreams",
        "Environment",
        "Outside",
        "Inside",
        "Reality",
        "Allies",
        "Enemies",
        "Evil",
        "Good",
        "Emotions",
        "Opposition",
        "War",
        "Peace",
        "The innocent",
        "Love",
        "The spiritual",
        "The intellectual",
        "New ideas",
        "Joy",
        "Messages",
        "Energy",
        "Balance",
        "Tension",
        "Friendship",
        "The physical",
        "A project",
        "Pleasures",
        "Pain",
        "Possessions",
        "Benefits",
        "Plans",
        "Lies",
        "Expectations",
        "Legal matters",
        "Bureaucracy",
        "Business",
        "A path",
        "News",
        "Exterior factors",
        "Advice",
        "A plot",
        "Competition",
        "Prison",
        "Illness",
        "Food",
        "Attention",
        "Success",
        "Failure",
        "Travel",
        "Jealousy",
        "Dispute",
        "Home",
        "Investment",
        "Suffering",
        "Wishes",
        "Tactics",
        "Stalemate",
        "Randomness",
        "Misfortune",
        "Death",
        "Disruption",
        "Power",
        "A burden",
        "Intrigues",
        "Fears",
        "Ambush",
        "Rumor",
        "Wounds",
        "Extravagance",
        "A representative",
        "Adversities",
        "Opulence",
        "Liberty",
        "Military",
        "The mundane",
        "Trials",
        "Masses",
        "Vehicle",
        "Art",
        "Victory",
        "Dispute",
        "Riches",
        "Status quo",
        "Technology",
        "Hope",
        "Magic",
        "Illusions",
        "Portals",
        "Danger",
        "Weapons",
        "Animals",
        "Weather",
        "Elements",
        "Nature",
        "The public",
        "Leadership",
        "Fame",
        "Anger",
        "Information"
    ]
};
